INCLUDE      := -I../include -I../../Thread/include -I../../Common/include -I../../extern/gtest-1.7.0/include

objs =
objs += SocketTest
objs += main
objs += EchoServer

TARGET=test

ROOT_DIR=../..

include ../../build/exec.mk

