LIBRARY_NAME := Messaging
INCLUDE      := -Iinclude -I../Common/include

objs = 
objs += Configure
objs += LocalTransport
objs += Message
objs += MessageQueue
objs += RouteConfig

ROOT_DIR = ..
include ../build/library.mk
